In [206]:
#import libraries

require 'numo/narray'
require 'ruby_linear_regression'
require 'daru'
require 'daru/plotly'
include Daru::Plotly::Methods # creates `plot` and `generate_data` method

#<Module:0x000000010dccd770>


### special thanks to the createors of these resources:
https://www.youtube.com/watch?v=km95-NMT6lU&t=280s - getting data set
https://v0dro.in/blog/2014/11/25/data-analysis-in-ruby-basic-data-manipulation-and-plotting/

In [188]:
#load data from csv
data = Daru::DataFrame.from_csv('dataset/atlanta-airport.csv')
df = data.dup

#<Daru::DataFrame(23110x48)>
               STATION       NAME       DATE       ACMH       ACSH       AWND       FMTM       FRGT       PGTM       PRCP       PSUN       SNOW       SNWD       TAVG       TMAX       TMIN       TSUN       WDF1       WDF2       WDF5       WDFG       WDFM       WESD       WSF1       WSF2       WSF5       WSFG       WSFM       WT01       WT02       WT03       WT04       WT05       WT06       WT07       WT08       WT09       WT11       WT13       WT14       WT15       WT16       WT17       WT18       WT19       WT21       WT22       WV03
          0 USW0001387 ATLANTA HA 1960-01-01        nil        nil        nil        nil        nil        nil       0.16        nil        0.0        0.0        nil         37         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          1 USW0001387 ATLANTA HA 1960-01-02        nil        nil        nil        nil        nil        nil       0.76        nil        0.0        0.0        nil         39         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          2 USW0001387 ATLANTA HA 1960-01-03        nil        nil        nil        nil        nil        nil       0.77        nil        0.0        0.0        nil         50         35        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          3 USW0001387 ATLANTA HA 1960-01-04        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         48         32        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          4 USW0001387 ATLANTA HA 1960-01-05        nil        nil        nil        nil        nil        nil       0.02        nil        0.0        0.0        nil         48         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          5 USW0001387 ATLANTA HA 1960-01-06        nil        nil        nil        nil        nil        nil       0.78        nil        0.0        0.0        nil         46         40        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          6 USW0001387 ATLANTA HA 1960-01-07        nil        nil        nil        nil        nil        nil        0.3        nil        0.0        0.0        nil         46         37        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          7 USW0001387 ATLANTA HA 1960-01-08        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         54         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          8 USW0001387 ATLANTA HA 1960-01-09        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         63         34        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          9 USW0001387 ATLANTA HA 1960-01-10        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         67         47        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         10 USW0001387 ATLANTA HA 1960-01-11        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         72         52        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         11 USW0001387 ATLANTA HA 1960-01-12        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         58         49        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         12 USW0001387 ATLANTA HA 1960-01-13        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         70         50        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         13 USW0001387 ATLANTA HA 1960-01-14        nil        nil        nil        nil        nil        nil       0.03        nil        0.0        0.0        nil         69         60        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         14 USW0001387 ATLANTA HA 1960-01-15        nil        nil        nil        nil        nil        nil       0.08        nil        0.0        0.0        nil         66         43        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         15 USW0001387 ATLANTA HA 1960-01-16        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         50         39        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         16 USW0001387 ATLANTA HA 1960-01-17        nil        nil        nil        nil        nil        nil       2.32        nil        0.0        0.0        nil         50         41        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         17 USW0001387 ATLANTA HA 1960-01-18        nil        nil        nil        nil        nil        nil       0.03        nil        0.0        0.0        nil         57         36        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         18 USW0001387 ATLANTA HA 1960-01-19        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         40         29        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         19 USW0001387 ATLANTA HA 1960-01-20        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         39         25        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         20 USW0001387 ATLANTA HA 1960-01-21        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         38         22        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         21 USW0001387 ATLANTA HA 1960-01-22        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         32         19        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         22 USW0001387 ATLANTA HA 1960-01-23        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         39         14        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         23 USW0001387 ATLANTA HA 1960-01-24        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         40         27        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         24 USW0001387 ATLANTA HA 1960-01-25        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         49         25        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         25 USW0001387 ATLANTA HA 1960-01-26        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         61         30        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         26 USW0001387 ATLANTA HA 1960-01-27        nil        nil        nil        nil        nil        nil       1.35        nil        0.0        0.0        nil         55         42        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         27 USW0001387 ATLANTA HA 1960-01-28        nil        nil        nil        nil        nil        nil       0.01        nil        0.0        0.0        nil         61         49        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         28 USW0001387 ATLANTA HA 1960-01-29        nil        nil        nil        nil        nil        nil        1.6        nil        0.0        0.0        nil         53         48        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         29 USW0001387 ATLANTA HA 1960-01-30        nil        nil        nil        nil        nil        nil       1.87        nil        0.0        0.0        nil         50         44        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...

In [218]:
df.type

NoMethodError: undefined method `type' for #<Daru::DataFrame(23110x48)>
               STATION       NAME       DATE       ACMH       ACSH       AWND       FMTM       FRGT       PGTM       PRCP       PSUN       SNOW       SNWD       TAVG       TMAX       TMIN       TSUN       WDF1       WDF2       WDF5       WDFG       WDFM       WESD       WSF1       WSF2       WSF5       WSFG       WSFM       WT01       WT02       WT03       WT04       WT05       WT06       WT07       WT08       WT09       WT11       WT13       WT14       WT15       WT16       WT17       WT18       WT19       WT21       WT22       WV03
          0 USW0001387 ATLANTA HA 1960-01-01        nil        nil        nil        nil        nil        nil       0.16        nil        0.0        0.0        nil         37         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          1 USW0001387 ATLANTA HA 1960-01-02        nil        nil        nil        nil        nil        nil       0.76        nil        0.0        0.0        nil         39         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          2 USW0001387 ATLANTA HA 1960-01-03        nil        nil        nil        nil        nil        nil       0.77        nil        0.0        0.0        nil         50         35        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          3 USW0001387 ATLANTA HA 1960-01-04        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         48         32        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          4 USW0001387 ATLANTA HA 1960-01-05        nil        nil        nil        nil        nil        nil       0.02        nil        0.0        0.0        nil         48         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          5 USW0001387 ATLANTA HA 1960-01-06        nil        nil        nil        nil        nil        nil       0.78        nil        0.0        0.0        nil         46         40        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          6 USW0001387 ATLANTA HA 1960-01-07        nil        nil        nil        nil        nil        nil        0.3        nil        0.0        0.0        nil         46         37        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
          7 USW0001387 ATLANTA HA 1960-01-08        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         54         33        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          8 USW0001387 ATLANTA HA 1960-01-09        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         63         34        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
          9 USW0001387 ATLANTA HA 1960-01-10        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         67         47        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         10 USW0001387 ATLANTA HA 1960-01-11        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         72         52        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         11 USW0001387 ATLANTA HA 1960-01-12        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         58         49        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         12 USW0001387 ATLANTA HA 1960-01-13        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         70         50        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         13 USW0001387 ATLANTA HA 1960-01-14        nil        nil        nil        nil        nil        nil       0.03        nil        0.0        0.0        nil         69         60        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         14 USW0001387 ATLANTA HA 1960-01-15        nil        nil        nil        nil        nil        nil       0.08        nil        0.0        0.0        nil         66         43        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         15 USW0001387 ATLANTA HA 1960-01-16        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         50         39        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         16 USW0001387 ATLANTA HA 1960-01-17        nil        nil        nil        nil        nil        nil       2.32        nil        0.0        0.0        nil         50         41        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         17 USW0001387 ATLANTA HA 1960-01-18        nil        nil        nil        nil        nil        nil       0.03        nil        0.0        0.0        nil         57         36        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         18 USW0001387 ATLANTA HA 1960-01-19        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         40         29        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         19 USW0001387 ATLANTA HA 1960-01-20        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         39         25        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         20 USW0001387 ATLANTA HA 1960-01-21        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         38         22        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         21 USW0001387 ATLANTA HA 1960-01-22        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         32         19        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         22 USW0001387 ATLANTA HA 1960-01-23        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         39         14        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         23 USW0001387 ATLANTA HA 1960-01-24        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         40         27        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         24 USW0001387 ATLANTA HA 1960-01-25        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         49         25        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil
         25 USW0001387 ATLANTA HA 1960-01-26        nil        nil        nil        nil        nil        nil        0.0        nil        0.0        0.0        nil         61         30        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         26 USW0001387 ATLANTA HA 1960-01-27        nil        nil        nil        nil        nil        nil       1.35        nil        0.0        0.0        nil         55         42        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         27 USW0001387 ATLANTA HA 1960-01-28        nil        nil        nil        nil        nil        nil       0.01        nil        0.0        0.0        nil         61         49        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         28 USW0001387 ATLANTA HA 1960-01-29        nil        nil        nil        nil        nil        nil        1.6        nil        0.0        0.0        nil         53         48        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
         29 USW0001387 ATLANTA HA 1960-01-30        nil        nil        nil        nil        nil        nil       1.87        nil        0.0        0.0        nil         50         44        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil        nil          1        nil        nil        nil        nil        nil        nil
        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...

# data clean up

In [189]:
# Add description for what eda is and why we must do it

In [190]:
df.shape

[23110, 48]

In [225]:
df.describe

#<Daru::DataFrame(5x45)>
                  ACMH       ACSH       AWND       FMTM       FRGT       PGTM       PRCP       PSUN       SNOW       SNWD       TAVG       TMAX       TMIN       TSUN       WDF1       WDF2       WDF5       WDFG       WDFM       WESD       WSF1       WSF2       WSF5       WSFG       WSFM       WT01       WT02       WT03       WT04       WT05       WT06       WT07       WT08       WT09       WT11       WT13       WT14       WT15       WT16       WT17       WT18       WT19       WT21       WT22       WV03
      count      11169      11169      14343      10188          1      14591      23109       6927      20469      21952       6336      23109      23109      13590       7001      10105      10088       9390       4166       5853       7001      10105      10088       9395       4166       9711       1382       3259        163        362        125         76       5468         40         30       2528        889         11       7985         32        318          5         35         10          2
       mean 55.0085056 58.9103769 8.23635013 1443.42854       78.0 1347.22184 0.13847764 60.4423271 0.00624847 0.00549380 63.7744633 72.0550867 52.7020641 412.304856 212.068275 215.256803 213.568596 216.688498 213.377340 0.00167435 16.1647478 17.9035032 23.3313243 23.7266098 16.6272443        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0        1.0
        std 33.0041677 35.1898749 3.23282853 864.532096        NaN 564.301583 0.38424784 35.4381687 0.13014303 0.10813089 14.2067644 15.2347348 15.3690306 275.436799 98.2667298 103.031234 104.145810 96.9862094 97.9768706 0.08916295 5.18533949 5.74898486 9.87553102 7.46585034 5.90624829        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0        0.0
        min          0          0       0.22          0         78          0        0.0          0        0.0        0.0          0         15         -8          0          0          0          0         23         45        0.0        0.0        0.0        0.0        2.2        4.9          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1
        max        100        100      28.19       9999         78       2936       6.68        100        7.9        5.0         91        106         82        864        360        360        370        360        360        6.7       59.9       49.0      340.0       77.0       68.9          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1          1

### To keep the data simple we will start the 5 core values as stated in the documentation:

#### The five core values are:
**PRCP** = Precipitation (mm or inches as per user preference, inches to hundredths on Daily Form pdf file) 

**SNOW** = Snowfall (mm or inches as per user preference, inches to tenths on Daily Form pdf file)

**SNWD** = Snow depth (mm or inches as per user preference, inches on Daily Form pdf file)

**TMAX** = Maximum temperature (Fahrenheit or Celsius as per user preference, Fahrenheit to tenths on Daily Form pdf file

**TMIN** = Minimum temperature (Fahrenheit or Celsius as per user preference, Fahrenheit to tenths on Daily Form pdf file

In [208]:
df_core = df['DATE','PRCP','SNOW','SNWD','TMAX','TMIN']
df_core.head(5) # print the top 5 values of the DataFrame

#<Daru::DataFrame(5x6)>
                  DATE       PRCP       SNOW       SNWD       TMAX       TMIN
          0 1960-01-01       0.16        0.0        0.0         37         33
          1 1960-01-02       0.76        0.0        0.0         39         33
          2 1960-01-03       0.77        0.0        0.0         50         35
          3 1960-01-04        0.0        0.0        0.0         48         32
          4 1960-01-05       0.02        0.0        0.0         48         33

In [209]:
df_core.describe

#<Daru::DataFrame(5x5)>
                  PRCP       SNOW       SNWD       TMAX       TMIN
      count      23109      20469      21952      23109      23109
       mean 0.13847764 0.00624847 0.00549380 72.0550867 52.7020641
        std 0.38424784 0.13014303 0.10813089 15.2347348 15.3690306
        min        0.0        0.0        0.0         15         -8
        max       6.68        7.9        5.0        106         82

In [210]:
df_core.size

23110

In [211]:
# def _dropNil!(row)
#   a_vector = Daru::Vector.new([])
#   row.each { |col| col.delete_row if col.nil?}
#   add_vector n, vector
# end



# def dropNil(df)
#   df.each(:row).each { |row| (puts containsNils(row)) }
# end

In [217]:
#handle nil values

def containsNil?(vector)
  vector.each { |col| return true if col.nil?}
  return false
end

# An array of vectorsdf_core_drop_nils
df_core_drop_nils = df_core.each(:row).map{|row| containsNil?(row) ? nil : row }.compact


# df_mod = df_core.each(:row).first
# temp = df_mod.dup

# df_mod[1] = nil

# df_with_nil = df_mod
# df_mod = temp

# puts df_with_nil.inspect
# puts df_mod.inspect



# puts containsNil?(df_with_nil)
# puts containsNil?(df_mod)
# puts df_mod.index

20393

In [220]:
# Turn the array of vectors back into dataframe
df_cleaned = Daru::DataFrame.rows(df_core_drop_nils)

#<Daru::DataFrame(20393x6)>
                  DATE       PRCP       SNOW       SNWD       TMAX       TMIN
          0 1960-01-01       0.16        0.0        0.0         37         33
          1 1960-01-02       0.76        0.0        0.0         39         33
          2 1960-01-03       0.77        0.0        0.0         50         35
          3 1960-01-04        0.0        0.0        0.0         48         32
          4 1960-01-05       0.02        0.0        0.0         48         33
          5 1960-01-06       0.78        0.0        0.0         46         40
          6 1960-01-07        0.3        0.0        0.0         46         37
          7 1960-01-08        0.0        0.0        0.0         54         33
          8 1960-01-09        0.0        0.0        0.0         63         34
          9 1960-01-10        0.0        0.0        0.0         67         47
         10 1960-01-11        0.0        0.0        0.0         72         52
         11 1960-01-12        0.0        0.0        0.0         58         49
         12 1960-01-13        0.0        0.0        0.0         70         50
         13 1960-01-14       0.03        0.0        0.0         69         60
         14 1960-01-15       0.08        0.0        0.0         66         43
         15 1960-01-16        0.0        0.0        0.0         50         39
         16 1960-01-17       2.32        0.0        0.0         50         41
         17 1960-01-18       0.03        0.0        0.0         57         36
         18 1960-01-19        0.0        0.0        0.0         40         29
         19 1960-01-20        0.0        0.0        0.0         39         25
         20 1960-01-21        0.0        0.0        0.0         38         22
         21 1960-01-22        0.0        0.0        0.0         32         19
         22 1960-01-23        0.0        0.0        0.0         39         14
         23 1960-01-24        0.0        0.0        0.0         40         27
         24 1960-01-25        0.0        0.0        0.0         49         25
         25 1960-01-26        0.0        0.0        0.0         61         30
         26 1960-01-27       1.35        0.0        0.0         55         42
         27 1960-01-28       0.01        0.0        0.0         61         49
         28 1960-01-29        1.6        0.0        0.0         53         48
         29 1960-01-30       1.87        0.0        0.0         50         44
        ...        ...        ...        ...        ...        ...        ...

In [227]:
#correlation matrix
df_cleaned.corr

#<Daru::DataFrame(5x5)>
                  PRCP       SNOW       SNWD       TMAX       TMIN
       PRCP        1.0 0.05311438 0.00447133 -0.0590020 0.06869435
       SNOW 0.05311438        1.0 0.35439069 -0.1061453 -0.0835515
       SNWD 0.00447133 0.35439069 1.00000000 -0.1169300 -0.1018700
       TMAX -0.0590020 -0.1061453 -0.1169300 0.99999999 0.91350346
       TMIN 0.06869435 -0.0835515 -0.1018700 0.91350346 0.99999999

Training a model